### ISSUE TITLE
Add Publisher Page Component

### ISSUE THREAD

**Issue by codenamejason** [Talent-DAO/JoDW-Demo#22]
Tasks:
- [x]  Add publisher page component

Figma: https://www.figma.com/file/yLdTBwuMagyq75JgfyjSSv/TalentDAO?node-id=1855%3A1665

<img width="710" alt="Screen Shot 2022-09-28 at 8 54 41 PM" src="https://user-images.githubusercontent.com/9419140/192914354-bec20015-74a5-42f3-b3f5-83ceb00f9e18.png">

**Comment by codecookerpro** [comment]
I have handled this issue along with issue#9 in 9-author-updates branch.
