### ISSUE TITLE
Lens protocol research

### ISSUE THREAD

**Issue by codenamejason** [Talent-DAO/JoDW-Demo#3]
- [x] Create Profile
- [x] Edit Profile
- [x] Follow Module(s)
- [x] Submit Publication
- [x] Edit Publication
- [x] Like Publication
- [x] Comment on Publication

**Comment by supriyaamisshra** [comment]
Here's my working doc
https://docs.google.com/document/d/1umxdOLACBpVANaJ2UKCxrvRTiAD1aJ65tnXnp1HY6TU/edit#
